fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-symlinks
      - id: detect-private-key
      - id: fix-byte-order-marker

  - repo: local
    hooks:
      - id: isort
        name: isort-local
        entry: isort
        language: python
        types: [python]
        exclude: .+/(settings|migrations)/.+
        pass_filenames: true
      - id: black
        name: black-local
        entry: black
        language: python
        types: [python]
        exclude: .+/(settings|migrations)/.+
        pass_filenames: true
      - id: missing-migrations
        name: missing-migrations-local
        entry: python manage.py makemigrations --check --dry-run
        language: system
        always_run: true
        pass_filenames: false
      - id: prospector
        name: prospector-local
        entry: prospector --messages-only
        language: python
        types: [python]
        exclude: .+/(settings|migrations)/.+
        pass_filenames: true
