# Generated by Django 3.1.5 on 2021-01-29 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='date',
        ),
        migrations.AddField(
            model_name='meeting',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='start date'),
        ),
        migrations.CreateModel(
            name='MeetingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True)),
                ('typee', models.CharField(choices=[('TALK', 'talk'), ('lightning_talk', 'lightning_talk'), ('DOJO', 'dojo'), ('PYPUDINHOS', 'pypudinhos'), ('INTERVAL', 'interval')], max_length=20, verbose_name='type')),
                ('starts_at', models.DateTimeField(verbose_name='starts at')),
                ('ends_at', models.DateTimeField(verbose_name='ends at')),
                ('hosts', models.ManyToManyField(blank=True, related_name='events', to='profiles.Profile', verbose_name='hosts')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='meetings.meeting', verbose_name='meeting')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
