name: Build pipeline

on:
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install DEV dependencies (for testing)
        run: pip install -r requirements-dev.txt

      - name: Style check
        run: prospector --messages-only

      - name: Imports check
        run: isort **/*.py --check-only

      - name: Security check
        run: bandit -x ./.venv -r .

      - name: Check missing migrations
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }} # TODO: Usar .env
        run: python manage.py makemigrations --check --dry-run

      - name: Update database schema
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }} # TODO: Usar .env
        run: python manage.py migrate

      - name: Tests check
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }} # TODO: Usar .env
        run: python manage.py test
